apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-test-java-web-app
  description: Tanzu Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
     'backstage.io/techdocs-ref' :  'app.kubernetes.io/part-of=tanzu-test-java-web-app'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
